[client]
name = "Client2"  # Different name
server_addresses = [
    "127.0.0.1:8001",
    "127.0.0.1:8002",
    "127.0.0.1:8003"
]

[requests]
rate_per_second =0.05
duration_seconds = 60.0
request_processing_ms = 20000
load_per_request = 0.2