[client]
name = "Client1"
server_addresses = [
    "10.40.39.41:8001",
    "10.40.38.47:8001",
    "10.40.51.153:8001"
]
image_dir = "test_images/secrets"

[requests]
# Total number of requests this client will send
total_requests = 50

# Random delay range between requests (milliseconds)
# Each request will wait a random time between min and max before sending the next one
min_delay_ms = 100
max_delay_ms = 2000