[client]
name = "Client1"
server_addresses = [
    "127.0.0.1:8001",
    "127.0.0.1:8002",
    "127.0.0.1:8003"
]
image_dir = "test_images/client1"
dos_address = "127.0.0.1:9000"
ip_address = "127.0.0.1"  # Change this to your public IP address

[requests]
total_requests = 10
min_delay_ms = 100
max_delay_ms = 500
