[client]
name = "Client2"  # Different name
server_addresses = [
    "10.40.50.111:8001",
    "10.40.38.47:8002",
    "10.40.50.111:8003"
]

[requests]
rate_per_second =0.05
duration_seconds = 60.0
request_processing_ms = 20000
load_per_request = 0.2