[client]
name = "Client2"
server_addresses = [
    "10.40.39.41:8001",
    "10.40.61.159:8002",
    "10.40.58.232:8003"
]
image_dir = "client_images/client2/original_images"
dos_address = "127.0.0.1:9000"
ip_address = "10.40.58.232"  # Change this to your public IP address

[requests]
total_requests = 10
min_delay_ms = 100
max_delay_ms = 500
