[server]
id = 1
address = "127.0.0.1:8001"

[peers]
peers = [
    { id = 2, address = "127.0.0.1:8002" },
    { id = 3, address = "127.0.0.1:8003" }
]

[election]
heartbeat_interval_secs = 1
monitor_interval_secs = 1
failure_timeout_secs = 3
election_timeout_secs = 2
