[server]
id = 2
address =  "10.40.38.47:8002"

[peers]
peers = [
    { id = 1, address = "10.40.50.111:8001" },
    { id = 3, address = "10.40.50.111:8003"}
]

[election]
heartbeat_interval_secs = 1
election_timeout_secs = 2
failure_timeout_secs = 3
monitor_interval_secs = 1

[encryption]
thread_pool_size = 4
max_queue_size = 100
