[server]
id = 1
address = "10.40.39.41:8001"
cover_image = "client_images/cover_images/cover_image.png"

[peers]
peers = [
    { id = 2, address = "10.40.61.159:8002" },
    { id = 3, address = "10.40.58.232:8003" }
]

[election]
heartbeat_interval_secs = 1
monitor_interval_secs = 1
failure_timeout_secs = 5
election_timeout_secs = 2
