[server]
id = 3
address = "127.0.0.1:8003"

[peers]
peers = [
    { id = 1, address = "127.0.0.1:8001" },
    { id = 2, address = "127.0.0.1:8002" }
]

[election]
heartbeat_interval_secs = 5
election_timeout_secs = 2
failure_timeout_secs = 15

[encryption]
thread_pool_size = 4
max_queue_size = 100

[metrics]
initial_load = 0.1
initial_reliability = 0.95
initial_response_time = 50.0