[server]
id = 1
address = "10.40.50.111:8001"

[peers]
peers = [
    { id = 2, address = "10.40.38.47:8002" },
    { id = 3, address = "10.40.50.111:8003" }
]

[election]
heartbeat_interval_secs = 5
election_timeout_secs = 2
failure_timeout_secs = 15

[encryption]
thread_pool_size = 4
max_queue_size = 100
